### ISSUE TITLE
NPE while building

### ISSUE THREAD

**Issue by twohey** [lewisd32/lint-maven-plugin#17]
I get the following NullPointerException in my build. Please let me know if you need more debugging information.

The error happens when I invoke `mvn verify package` but not `mvn verify` or `mvn package`.

```
[ERROR] Failed to execute goal com.lewisd:lint-maven-plugin:0.0.8:check (lint-maven) on project payments-api: Error while performing check: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.lewisd:lint-maven-plugin:0.0.8:check (lint-maven) on project payments-api: Error while performing check
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error while performing check
        at com.lewisd.maven.lint.plugin.CheckMojo.executeRule(CheckMojo.java:160)
        at com.lewisd.maven.lint.plugin.CheckMojo.executeRules(CheckMojo.java:151)
        at com.lewisd.maven.lint.plugin.CheckMojo.execute(CheckMojo.java:107)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.lang.NullPointerException
        at com.lewisd.maven.lint.rules.basic.GroupArtifactVersionMustBeInCorrectOrderRule$InputLocationMapValueComparator.compare(GroupArtifactVersionMustBeInCorrectOrderRule.java:135)
        at com.lewisd.maven.lint.rules.basic.GroupArtifactVersionMustBeInCorrectOrderRule$InputLocationMapValueComparator.compare(GroupArtifactVersionMustBeInCorrectOrderRule.java:131)
        at java.util.TreeMap.put(TreeMap.java:545)
        at com.lewisd.maven.lint.rules.basic.GroupArtifactVersionMustBeInCorrectOrderRule.invoke(GroupArtifactVersionMustBeInCorrectOrderRule.java:83)
        at com.lewisd.maven.lint.RuleInvoker.invokeRule(RuleInvoker.java:21)
        at com.lewisd.maven.lint.plugin.CheckMojo.executeRule(CheckMojo.java:158)
        ... 23 more
[ERROR] 
```

**Comment by lewisd32** [comment]
Sorry for the incredibly delayed response to this.
I've just fixed some ugly `null`s I was passing around, and I believe it should fix this bug.
I know it's been a year, so I don't really expect a response, or that you'll have the code around to try running this still, but if by any chance you do... I'd certainly appreciate knowing if it's actually fixed.

**Comment by lewisd32** [comment]
I forgot to mention, I haven't done a release with this fix yet, so you'll need to build from master if you want to test it.

**Comment by lkwg82** [comment]
Did you released already one?

**Comment by lewisd32** [comment]
Unfortunately, I've been having some problems with the computer I usually use to work on this, and can't even get it to build. :(  So I haven't done a release.

**Comment by lkwg82** [comment]
Can you fix your computer to do a release?

**Comment by lewisd32** [comment]
I got things building on a different computer and verified the things I wanted to check before doing a release.  I've released 0.0.9, and it should be filtering through to maven central shortly.

**Comment by lkwg82** [comment]
Great! It is available.

**Comment by twohey** [comment]
When I use version 0.0.9 it appears that the <onlyRunRules> section is not honored

**Comment by lkwg82** [comment]
If the NPE is gone, plz close this!

**Comment by lewisd32** [comment]
@twohey this is reported in #23,6 so I'm closing this since the NPE it reported is gone.
